<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head id="Head1">
    <title>	My Calendar </title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
			<link href="/calendar/css/dailog.css" rel="stylesheet" type="text/css" />
			<link href="/calendar/css/calendar.css" rel="stylesheet" type="text/css" /> 
			<link href="/calendar/css/dp.css" rel="stylesheet" type="text/css" />   
			<link href="/calendar/css/alert.css" rel="stylesheet" type="text/css" /> 
			<link href="/calendar/css/main.css" rel="stylesheet" type="text/css" /> 
			<link href="/calendar/css/dropdown.css" rel="stylesheet" /> 
			<link href="/calendar/css/colorselect.css" rel="stylesheet" />  

			<script src="/calendar/src/jquery.js" type="text/javascript"></script>  

			<script src="/calendar/src/Plugins/Common.js" type="text/javascript"></script>    
			<script src="/calendar/src/Plugins/datepicker_lang_US.js" type="text/javascript"></script>     
			<script src="/calendar/src/Plugins/jquery.datepicker.js" type="text/javascript"></script>

			<script src="/calendar/src/Plugins/jquery.form.js" type="text/javascript"></script>     
			<script src="/calendar/src/Plugins/jquery.validate.js" type="text/javascript"></script> 

			<script src="/calendar/src/Plugins/jquery.dropdown.js" type="text/javascript"></script>     
			<script src="/calendar/src/Plugins/jquery.colorselect.js" type="text/javascript"></script>  

			<script src="/calendar/src/Plugins/jquery.alert.js" type="text/javascript"></script>    
			<script src="/calendar/src/Plugins/jquery.ifrmdailog.js" defer="defer" type="text/javascript"></script>
			<script src="/calendar/src/Plugins/wdCalendar_lang_US.js" type="text/javascript"></script>    
			<script src="/calendar/src/Plugins/jquery.calendar.js" type="text/javascript"></script>   

	</head>
	<body>
		<?php echo $this->content ?>
	</body>
</html>
